chore: Refactor build and install instructions in pkgmk.in

diff --git a/pkgmk.in b/pkgmk.in
--- a/pkgmk.in
+++ b/pkgmk.in
@@ -562,19 +562,28 @@ build_package() {
 		warning "Packages should be built as root."
 	fi
 
-	info "Building '$TARGET'."
+	info "Building package of '$TARGET'."
 
 	unpack_source
 
-	info "Executing build instructions for '$TARGET'."
+	local _part
 
-	cd $SRC
-	set -e -x ; build || exit $E_BUILD
+	# Create trap if the build exits prematurely
+	trap "Something went wrong with '$_part'" EXIT
 
-	info "Executing install instructions for '$TARGET'."
+    for part in build install; do
+		if [ "$part" = "build" ]; then
+		    _part="build"
+			cd $SRC
+			build
+		else
+		    _part="build"
+			cd $SRC
+			install
+		fi
+	done
 
-	cd $SRC
-	set -e -x ; install || exit $E_INSTALL
+	trap - EXIT
 
 	if [ $? = 0 ]; then
 		if [ "$PKGMK_NO_STRIP" = "no" ]; then
@@ -615,7 +624,7 @@ build_package() {
 		if [ -f $TARGET ]; then
 			touch -r $PKGMK_ROOT/$PKGMK_PKGFILE $TARGET &> /dev/null
 		fi
-		error "Building '$TARGET' failed."
+		error "Building package of '$TARGET' failed."
 		exit 1
 	fi
 }
@@ -741,6 +750,17 @@ interrupted() {
 	exit 1
 }
 
+died() {
+	echo ""
+	error "Died: $@"
+
+	if [ "$PKGMK_KEEP_WORK" = "no" ]; then
+		rm -rf $PKGMK_WORK_DIR
+	fi
+
+	exit 1
+}
+
 print_help() {
 	echo "usage: `basename $PKGMK_COMMAND` [options]"
 	echo "options:"
@@ -854,12 +874,6 @@ parse_options() {
 }
 
 main() {
-	# multilib
-	PKGMK_ARCH=64
-	if [ -f ".32bit" ]; then
-		PKGMK_ARCH=32
-	fi
-
 	local FILE TARGET
 
 	parse_options "$@"
